name: ActionsTest


on: [push]


jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]


    steps:
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '84.0.4147.30'
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install 
      run: npm install
        

    - name: test
      run: npm run chrome
    
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: test