name: ActionsTest


on: [push]


jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      node:
        node-version: [12.x]


    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ node.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ node.node-version }}
    - name: install 
      run: npm install

    - name: build 
      run: tsc

    - name: test
      run: npm run local
    
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: test