name: ActionsTest


on: [push]
env:
  BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
  BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"

jobs:
  build:


    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]


    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: install 
      run: npm install

    - name: build 
      run: tsc

    - name: test
      run: npm run local

    - name: Allure report
      uses: afiore/action-allure-report@v0.1.0
